language: java
addons:
  sonarcloud:
    organization: "synus-org"
script:
  - ./gradlew sonarqube
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
